# Generated by Django 4.0.4 on 2022-07-29 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hour',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Task vaqti'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Task nomi'),
        ),
    ]
