# Generated by Django 4.0.4 on 2022-07-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_hour_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hour',
            field=models.DateTimeField(blank=True, verbose_name='Task vaqti'),
        ),
    ]
